I filled the tables for ingredients, recipes and alternatives
peterst5/ethical-eating pull request #37
Opened 2020-11-30 02:36 UTC by jcccookie

2020-11-30 03:05 UTC, Jack-Edwards commented on database/scripts/ingredientAlternativeData.js
> +    ['67', '95'],
I haven't looked at the ingredient alternative code in a while.  Is this list saying ingredient with id=67 has multiple alternatives?

2020-11-30 03:06 UTC, Jack-Edwards commented
Looks good to me.  Just the one question that I'm curious about

2020-11-30 03:06 UTC, Jack-Edwards approved these changes

2020-11-30 03:08 UTC, peterst5 commented on database/scripts/ingredientAlternativeData.js
> +    ['67', '95'],
Yeah, so the ingredients should have MULTIPLE alternatives if possible. The first 2 were ones that I out in to check my modal.

2020-11-30 03:09 UTC, jcccookie commented on database/scripts/ingredientAlternativeData.js
> +    ['67', '95'],
Yes, it looks like mozzarella has two alternatives, pasture-raised and vegan mozzarella. I think ingredients can have multiple alternatives.

2020-11-30 03:09 UTC, peterst5 requested changes
Each ingredient should have more than 1 alternative if possible.

2020-12-01 02:41 UTC, peterst5 approved these changes

2020-12-01 02:41 UTC, merged